meta:
  title: Zenegy dev portal
  description: The best API documentation generator ever.
  siteUrl: https://zenegy.com
headerIcon: ./images/zenegy-icon-white.png
enableToc: true
oasDefinitions:
    # documents: ./openapi/documents.yaml
    # admin: ./openapi/admin.yaml
  documents: https://api.redoc.ly/registry/zenegy-kca/documents/v1/bundle/default/openapi.yaml
  admin:   https://api.redoc.ly/registry/zenegy-kca/admin/v1/bundle/default/openapi.yaml
  # hours: https://api.redoc.ly/registry/zenegy-kca/hours/v1/bundle/default/openapi.yaml
  numbers: https://api.redoc.ly/registry/zenegy-kca/numbers/v1/bundle/default/openapi.yaml
  # payrol-dk: https://api.redoc.ly/registry/zenegy-kca/payroll-dk/v1/bundle/default/openapi.yaml
  # add links to definitions in our API registry by using a fully qualified URL.
stylesheets:
  - https://fonts.googleapis.com/css?family=Roboto:300,400,600,700
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap
#ga:
  # you can use any options here from https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/
  # note that GA doesn't work in DEV
#  trackingId: UA-45997213-1
#scripts:
#  - ./static/intercom.js
auth:
  idps:
    main:
      type: oidc
      configurationUrl: https://auth.zenegy.com/.well-known/openid-configuration
      clientId:  cf86d0b437245ad8ebce4d7291183b6
      clientSecret: MzIwMWExMGZhOTcyNDExOTkwYTk2NDY3N2UzMDYzZDk=
      scopes:
        - scope:hours
nav:

  - label: Api Reference
    page: developer-portal/index.md

  - label: External docs
    icon: ./images/redocly-icon-white.png
    href: https://docs.redoc.ly/developer-portal/introduction/

  - search: true

footer:
  copyrightText: © Zenegy ApS 2021
  columns:
    - group: Legal
      items:
        - label: Terms of Use
          href: 'https://zenegy.com/en/terms-of-service/'
        - label: Privacy Notice
          href: 'https://zenegy.com/en/data-processing/'
        - label: Cookie Notice
          href: 'https://redoc.ly/privacy-policy/'
    - group: Support
      items:
        - label: FAQ
          page: faq.md
        - label: Contact us
          page: contact.mdx
